### PR TITLE
Refactor website under Middleman framework

### PR DESCRIPTION
**Pull request by alexcu**
This pull request changes the underlying framework of the website from Jekyll to [Middleman](http://middlemanapp.com) to improve the operability with Ruby. This will improve the website by primarily through the use of helper functions. A list of major changes are described below:

### Support for code snippets via the `code_snippet` helper function

A new `code_snippet` helper function can be used to automatically generate tabs with each language in markdown files. Refer to https://github.com/macite/splashkit/commit/1453eb5b5bb22000431f964fff4c6771a02c19bc. At present, this uses GitHub gists to resolve the examples, but this can be changed later on. The gists could provide a centralised place to store all snippets—the gist information is read out of the `data/code_snippets.yml` file.

```erb
<div> <!-- wrap HTML in a div -->
    <%= code_snippet data.code_snippets.getting_started.gist_id, data.code_snippets.getting_started.filename %>
</div>
```

### GitHub-flavoured Markdown

You can insert code using GitHub-flavoured Markdown. E.g.

    ```ruby
    puts "Look at my ruby code!"
    ````

### Directory indexes are added for "pretty" urls

From now on, directory indexes are used for pretty urls. E.g.:

```
foo/bar/qux.md.erb
```

maps to

```
foo/bar/qux/
```

### Webpage titles are automatically generated based on the sitemap

The `<title>` tag will be generated based on the URL. E.g.:

```
docs/getting-started/index.html
```

will generate a page title of

```
Docs - Getting Started
```

This is always added to `SplashKit` so that `SplashKit` remains prefixed to all titles.

In the case of `/index.html`, 'Home' is appended instead.

### Other changes:

- Font-Awesome is added
- SASS support

### CODE REVIEW

**Comment by macite** [comment]
Given that we are going to build the Jekyll site using Middleman -- wouldn't we put the Middleman site details on the `master` branch so that the docs are with the project and then when we build only push the resulting site details to `gh-pages`?

**Comment by alexcu** [comment]
I believe it's fine to include the README for the website under `gh-pages` but I see what you mean. I would think that anything on `master` refers to just the SplashKit SDK, and not its website.

I'm pretty sure that GitHub deployment under middleman will push only the built `site` folder (not the `source` or root folders) so it doesn't matter so long as we configure it that way. It doesn't even need to be Jekyll—you can serve any `index.html` and gh-pages will render that.

I'll review this though with other gh-pages websites that use Middleman over the Jekyll framework and see how they do it. Let me do that before we finalise the PR and I'll get back to you @macite.

**Comment by macite** [comment]
Remember that we are also going to be generating large parts of the documentation from the API itself. If these are on different branches that will make it more complicated.

**Comment by alexcu** [comment]
Right, I thought we were going to run the API parser and spit out some sort of YAML file to place under the `data` directory. E.g have a git hook on each commit or build script that re-runs the parser, checks out `gh-pages`, spits the output under `data` and runs `middleman deploy`. That way the API is kept constantly up-to-date with each commit. Maybe I should play around with the parser first and clarify my understanding on how it works so we're both on the same page on this 😊

**Comment by macite** [comment]
I think we'd only run it on new "release" versions so the website documentation remains in sync with the release code. For me I was thinking of this more as the documentation rather than the website -- so it is related to the project. Having it in master would link it to the API state -- so you checkout release x you get its code and documentation. So perhaps its a bit of both -- the documentation is on master (will be most of the md files, as well as the data from the api etc) and this can be pushed over to `gh-pages` to be "published" -- thereby allowing us to keep multiple versions of the documentation as well.

**Comment by alexcu** [comment]
I see now, yes good idea with having each version up. We could get fancy and have the pages generated directly from, say, each `release/x` branch which generates the pages at build time but that could be overkill. Is the parser finalised anywhere? I'm thinking perhaps it's not a good idea to keep it in Markdown since if we want to make changes to the structure of the API documentation we'd need to re-write each Markdown file (whereas having it in YAML would mean we store it solely as a "data" file which we could structure anyway we want—decoupling the semantics from the way it's presented). Maybe we do both? Anyhow still early days, we can discuss this later on.

**Comment by macite** [comment]
The parser is already there but is generating the html for the API on the SwinGame site (as well as generating the various language variations of SwinGame). So just need to write the code to traverse the object model and output YAML.

**Comment by alexcu** [comment]
Sounds good. Can help out with that.

**Comment by macite** [comment]
Sounds good. For the moment, should I merge this in?

**Comment by alexcu** [comment]
Sure 😊

**Pull request merged**
